[versions]
ktor = "3.0.3"

[plugins]
vanniktech-mavenPublish = { id = "com.vanniktech.maven.publish", version = "0.29.0" }

[libraries]
ktor-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-contentnegotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-log = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-mock = { module = "io.ktor:ktor-client-mock", version.ref = "ktor" }
logback = { module = "ch.qos.logback:logback-classic", version = "1.5.16" }

[bundles]
ktor = ["ktor-json", "ktor-cio", "ktor-core", "ktor-contentnegotiation", "ktor-log"]